### ISSUE TITLE
博文链接炸了

### ISSUE THREAD

**Issue by crossPQW** [shaojiankui/iOS-WebView-JavaScript#1]
博文链接炸了，应该是CSS加载失败。

**Comment by shaojiankui** [comment]
https去掉s就行了。之前博客开了https

**Comment by xhdrq** [comment]
您好，问您一个问题，就是h5跳转到原生登录界面登录成功之后返回到h5然后怎么来刷新h5呢

**Comment by shaojiankui** [comment]
@dairuiquan  拿到药跳转的url 新创建一个request webview load就行了
